# Identificadores del proyecto
sonar.projectKey=leoneltql_rayogopfm
sonar.projectName=RayoGoPFM
sonar.projectVersion=1.0.0
sonar.organization=leoneltql
sonar.host.url=https://sonarcloud.io

# Código fuente
sonar.sources=backend/src,lib

# Pruebas
sonar.tests=backend/test,test
sonar.test.inclusions=backend/test/**/*.test.js,test/**/*_test.dart

# Exclusiones
sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/.dart_tool/**,**/.idea/**,**/.flutter-plugins-dependencies,**/.metadata,**/android/**,**/ios/**,**/linux/**,**/macos/**,**/windows/**,**/web/**,**/Dockerfile,**/docker-compose.yml,backend/database/**,backend/scripts/**

# Cobertura
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.coverage.exclusions=backend/scripts/**,backend/database/**

# Fallar el workflow si no pasa SonarCloud
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
